# Generated by Django 4.0.6 on 2022-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_img', models.ImageField(upload_to='images/')),
                ('pencil_drawing', models.ImageField(upload_to='images/')),
                ('picture_framing', models.ImageField(upload_to='images/')),
                ('gift_box', models.ImageField(upload_to='images/')),
                ('greeting_card', models.ImageField(upload_to='images/')),
                ('training', models.ImageField(upload_to='images/')),
                ('appears', models.ImageField(upload_to='images/')),
                ('review1', models.ImageField(upload_to='images/')),
                ('review2', models.ImageField(upload_to='images/')),
                ('review3', models.ImageField(upload_to='images/')),
                ('review4', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
