# Generated by Django 4.0.6 on 2022-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='carousel',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
