# Generated by Django 4.0.6 on 2022-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_enquires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquires',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
