# Generated by Django 4.0.6 on 2022-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_enquires_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquires',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
