# Generated by Django 4.0.6 on 2022-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_enquires_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquires',
            name='time_added',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
