# Generated by Django 4.0.6 on 2022-08-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_enquires_time_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquires',
            old_name='admin',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='enquires',
            old_name='client',
            new_name='sender',
        ),
    ]
