# Generated by Django 4.0.6 on 2022-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Pencil Drawings', 'Pencil Drawings'), ('Picture Framing', 'Picture Framing'), ('Gift Boxes', 'Gift Boxes'), ('Greeting Cards', 'Greeting Cards'), ('Display', 'Display')], max_length=30),
        ),
    ]
