# Generated by Django 4.0.6 on 2022-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='giftbox', max_length=200),
        ),
    ]
