# Generated by Django 4.0.6 on 2022-08-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pencil Drawings', 'Pencil Drawings'), ('Picture Framing', 'Picture Framing'), ('Gift Boxes', 'Gift Boxes'), ('Greeting Cards', 'Greeting Cards')], max_length=30)),
                ('price1', models.FloatField(blank=True, null=True)),
                ('price2', models.FloatField(blank=True, null=True)),
                ('price3', models.FloatField(blank=True, null=True)),
                ('price4', models.FloatField(blank=True, null=True)),
                ('price5', models.FloatField(blank=True, null=True)),
                ('price6', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
